# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=140)),
                ('plot', models.TextField()),
                ('tahun', models.PositiveIntegerField()),
                ('rating', models.IntegerField(choices=[(0, 'tr - tanpa rating'), (1, 'ru - umum'), (2, 'ro - pengawasan ortu'), (3, 'rb - dibatasi')], default=0)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
