# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='runtime',
            field=models.PositiveIntegerField(default=90),
            preserve_default=False,
        ),
    ]
