# Generated by Django 2.1.5 on 2019-01-29 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0002_film_runtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_awal', models.CharField(max_length=140)),
                ('nama_akhir', models.CharField(max_length=140)),
                ('lahir', models.DateField()),
                ('mati', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('nama_akhir', 'nama_awal'),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=140)),
            ],
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('-tahun', 'judul')},
        ),
        migrations.AddField(
            model_name='role',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='film_app.Film'),
        ),
        migrations.AddField(
            model_name='role',
            name='orang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='film_app.Orang'),
        ),
        migrations.AddField(
            model_name='film',
            name='aktors',
            field=models.ManyToManyField(blank=True, through='film_app.Role', to='film_app.Orang'),
        ),
        migrations.AddField(
            model_name='film',
            name='direktur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarahkan', to='film_app.Orang'),
        ),
        migrations.AddField(
            model_name='film',
            name='pengarangs',
            field=models.ManyToManyField(blank=True, related_name='menulis_kredit', to='film_app.Orang'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('film', 'orang', 'nama')},
        ),
    ]
